import { baseRoute } from '../../constants/routes'

export const CALENDAR_ROUTE = baseRoute + '/calendars'
export const CALENDAR_PLAYER_ROUTE = baseRoute + '/calendar'

export const CREATE_CALENDAR = 'CREATE_CALENDAR'
export const CREATE_CALENDAR_SUCCESS = 'CREATE_CALENDAR_SUCCESS'

export const GET_PLAYER_CALENDAR = 'GET_PLAYER_CALENDAR'
export const GET_PLAYER_CALENDAR_SUCCESS = 'GET_PLAYER_CALENDAR_SUCCESS'

export const GET_ALL_CALENDARS = 'GET_ALL_CALENDARS'
export const GET_ALL_CALENDARS_SUCCESS = 'GET_ALL_CALENDARS_SUCCESS'

export const GET_CALENDAR = 'GET_CALENDAR'
export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS'

export const UPDATE_CALENDAR = 'UPDATE_CALENDAR'
export const UPDATE_CALENDAR_SUCCESS = 'UPDATE_CALENDAR_SUCCESS'