import { baseRoute } from '../../../../constants/routes'

export const ANSWERS_HATCH_ROUTE = baseRoute + '/answers'

export const CREATE_HATCH_ANSWER = 'CREATE_HATCH_ANSWER'
export const CREATE_HATCH_ANSWER_SUCCESS = 'CREATE_HATCH_ANSWER_SUCCESS'

export const UPDATE_HATCH_ANSWER = 'UPDATE_HATCH_ANSWER'
export const UPDATE_HATCH_ANSWER_SUCCESS = 'UPDATE_HATCH_ANSWER_SUCCESS'

export const DELETE_HATCH_ANSWER = 'DELETE_HATCH_ANSWER'
export const DELETE_HATCH_ANSWER_SUCCESS = 'DELETE_HATCH_ANSWER_SUCCESS'